source: src/FederationLib
default_build: release
entry_point: main
web_entry_point: web
update_source: nosial/federationlib@n64
repository:
  name: n64
  type: github
  host: git.n64.cc
  ssl: true
assembly:
  name: FederationLib
  package: net.nosial.federation
  version: 1.0.0
dependencies:
  net.nosial.configlib: nosial/configlib@github
  net.nosial.loglib2: nosial/loglib2@github
  net.nosial.optslib: nosial/optslib@github
  com.symfony.uid: symfony/uid@packagist
execution_units:
  -
    name: main
    type: php
    mode: auto
    entry: main
  -
    name: web
    type: web
    mode: auto
    entry: web_entry
build_configurations:
  -
    name: release
    output: target/release/net.nosial.federation.ncc
    type: ncc
  -
    name: web_release
    output: target/web/net.nosial.federation.ncc
    type: ncc
    options:
      static: true
    definitions:
      NCC_DISABLE_LOGGING: true
  -
    name: debug
    output: target/debug/net.nosial.federation.ncc
    type: ncc
    definitions:
      DEBUG: '1'
