<?php

    namespace FederationServer\Classes\Enums;

    enum AuditLogType : string
    {
        case OTHER = 'OTHER';
        case OPERATOR_CREATED = 'OPERATOR_CREATED';
        case OPERATOR_DELETED = 'OPERATOR_DELETED';
        case OPERATOR_DISABLED = 'OPERATOR_DISABLED';
        case OPERATOR_ENABLED = 'OPERATOR_ENABLED';

        case ATTACHMENT_UPLOADED = 'ATTACHMENT_UPLOADED';
        case ATTACHMENT_DELETED = 'ATTACHMENT_DELETED';

        case EVIDENCE_CREATED = 'EVIDENCE_CREATED';
        case EVIDENCE_DELETED = 'EVIDENCE_DELETED';

        case ENTITY_DISCOVERED = 'ENTITY_DISCOVERED';
        case ENTITY_BLACKLISTED = 'ENTITY_BLACKLISTED';
        case ENTITY_UNBLACKLISTED = 'ENTITY_UNBLACKLISTED';
    }
